[dev]
    command = "npm run start"
    framework = "#custom"
    autoLaunch = true
    publish = "public"
    targetPort = 3000

[build.environment]
  NPM_CONFIG_USERCONFIG = "./netlify/.npmrc"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true