import { useAppDispatch, useAppSelector } from "../../app/hooks";
import { useParams, useRouteMatch } from "react-router-dom";

import { fetchCitiesWithCountThunk, selectors } from "./vaccinationCitiesSlice";

import { FetchState } from "../FetchState";
import React from "react";
import VaccinationCityGroup from "./VaccionationCityGroup";
import { ResultFetchError } from "../../ResultComponents";

import { Row, Col, Typography } from "antd";

type CityParams = {
  province: string;
  district?: string;
};

/**
 * Cities is a component that provides all the cities
 *
 * City is a concept that's generated by us and according to the
 * data provided by NCOC there's no such abstraction,
 *
 * so at the very basic level city is something that's considered
 * to be (Province + District + Tehsil)
 *q
 * In cases where we have only one district, the city component would automatically
 * list all the tehsils. This happens in the case of Islamabad. I am not aware
 * of any other ones.
 *
 * Rest assured Cities component is going to display both
 * Province and District along with Tehsil to omit any sort of confusions
 *
 */
export default function Cities() {
  const dispatch = useAppDispatch();

  const fetchState = useAppSelector(selectors.selectFetchState);
  const isLoading = fetchState === FetchState.pending;
  const isRejected = fetchState === FetchState.rejected;

  const title = `All Cities`;

  if (isRejected) {
    return <ResultFetchError />;
  }

  if (fetchState === FetchState.idle) {
    dispatch(fetchCitiesWithCountThunk());
  }

  return (
    <React.Fragment>
      <Row className="pageHeader">
        <Col span={24}>
          <Typography.Title>{title}</Typography.Title>
        </Col>
      </Row>
      <Row className="cards-body">
        <Col span={24}>
          <VaccinationCityGroup
            itemsInRow={5}
            isLoading={isLoading}
          />
        </Col>
      </Row>
    </React.Fragment>
  );
}
