import VaccinationGroups from "./VaccinationGroups";
import { useAppDispatch, useAppSelector } from "../../app/hooks";
import { useParams, useRouteMatch } from 'react-router-dom'


import {
  groupsSelectors,
  fetchCitiesWithCountThunk,
  selectCitiesByFilter,
  selectors
} from "./vaccinationGroupsSlice";
import { CityWithCount } from "../../api/vaccinationsFakeAPI";
import { useDispatch } from "react-redux";
import { FetchState } from "../types";
import React from "react";
import { Row, Col } from "antd";
import VaccinationCityGroup from "./VaccinationGroups";

type CityParams = {
  province: string;
  district?: string;
}

/**
 * Cities is a component that provides all the cities
 *
 * City is a concept that's generated by us and according to the
 * data provided by NCOC there's no such abstraction,
 *
 * so at the very basic level city is something that's considered
 * to be (Province + District + Tehsil)
 *q
 * In cases where we have only one district, the city component would automatically
 * list all the tehsils. This happens in the case of Islamabad. I am not aware
 * of any other ones.
 *
 * Rest assured Cities component is going to display both
 * Province and District along with Tehsil to omit any sort of confusions
 *
 */
export default function Cities() {
  const dispatch = useAppDispatch()
  const { district, province } = useParams<{province?: string; district?:string;}>()
  const filter = province ? { district, province } : null

  const title = !filter ?
    `Cities in ${district ? district + '/' : ''}${province}` :
    `All cities`


  const cities : CityWithCount[] = useAppSelector((state) => selectCitiesByFilter(state, filter))
  const fetchState = useAppSelector(selectors.selectFetchState)
  const isLoading = fetchState === FetchState.pending
  const isRejected = fetchState === FetchState.rejected

  if (fetchState === FetchState.idle) {
    dispatch(fetchCitiesWithCountThunk())
  }

  return (
    <React.Fragment>
      <Row className="pageHeader">
        <Col span={24}><h1>{title}</h1></Col>
      </Row>
      <Row className="cards-body">
        <VaccinationCityGroup fetchState={fetchState} cities={cities} />
      </Row>
    </React.Fragment>
  )
}

